name: Deploy ke Azure VM

on:
    push:
        branches:
            - deployment

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Production-VM

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm install

            - name: Build React App
              run: npm run build

            - name: Deploy to Azure VM Via SSH
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.VM_HOST }}
                  username: ${{ secrets.VM_USER }}
                  key: ${{ secrets.PUB_SSH_KEY }}
                  source: "build/*"
                  target: ${{ secrets.VM_TARGET }}
